### ISSUE TITLE
Bug !! do login!!

### ISSUE THREAD

**Issue by bulacha2** [carlosroberto555/healthyliving#9]
Descobrir uma maneira de corrigir o bug onde o se usuário  alterar o nome dele no arquivo que é gerado automaticamente pelo programa, continua sendo possível utilizar o programa.

```
Arquivo userdata.dat
```

**Comment by carlosroberto555** [comment]
Pensaremos em uma alternativa, acho que talvez utilizar a sessão do usuário no lugar do nome possa corrigir. Contudo ao ler a sessão o aplicativo vai perguntar ao servidor se a sessão é válida.
